# 这个 custom-values.yaml 相当于 chart 中 values.yaml 的一个 patch

# 指标告警管理器，可通过插件实现钉钉群报警：https://github.com/timonwong/prometheus-webhook-dingtalk
## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  enabled: false

## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:
  enabled: true

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  adminPassword: prom-operator

  service:
    portName: service

    type: NodePort
    nodePort: 30880

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true

  # Prometheus-Operator v0.39.0 and later support TLS natively.
  tls:
    enabled: true
  
  service:
    nodePort: 30080
    nodePortTls: 30443
    type: NodePort

  nodeSelector: {}

## Deploy a Prometheus instance
prometheus:
  enabled: true

  service:
    nodePort: 30090
    type: NodePort

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:
    ## Define which Nodes the Pods are scheduled on.
    ## ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    # 指标保留时长
    # 建议集群内部的 prometheus 只做指标中转（短时间存储），长期存储放在外部的联邦集群。
    retention: 8h

    # （实验性特性）指标可用的存储空间大小，达到这个值后，会从最老的指标开始进行清理。
    retentionSize: ""

    ## Enable compression of the write-ahead log using Snappy.
    ##
    walCompression: false
