# 本地开发测试集群部署 istio，需要用到的自定义配置
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  # profile=default 下只部署 pilot/ingressgateway/prometheus
  profile: default
  hub: registry.xxx.local/istio  # 使用私有 dockerhub 镜像仓库
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 1000m # override from default 500m
            memory: 4096Mi # ... default 2048Mi
        hpaSpec:
          maxReplicas: 3 # ... default 5
          minReplicas: 2  # ... default 1
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:  # 实测发现这东西还挺吃资源的
              cpu: 2000m
              memory: 2048Mi
          hpaSpec:
            maxReplicas: 5 # ... default 5
            minReplicas: 2  # ... default 1
          service:  # 测试集群需通过 NodePort 导出 ingressgateway
            ports:
            - name: status-port
              port: 15020
              targetPort: 15020
            - name: http2
              port: 80
              nodePort: 80
              targetPort: 80
            - name: https
              port: 443
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tcp
              port: 31400
  values:
    global:  # 全局配置
      defaultNodeSelector:
        network: "true"     # 使用网络组件专用节点
      jwtPolicy: first-party-jwt  # 不使用第三方 jwt 验证。
      proxy:
        logLevel: info  # 开发环境，启用更详细的日志输出
        tracer: zipkin
      tracer:
        zipkin:  # 目前 istio 只支持 zipkin 的协议格式（x-b3-xxx 请求头），还不支持 w3c trace-context 标准
          address: "<jaeger-collector-service>.<jaeger-collector-namespace>:9411"  # 应该也可以配置外部 url
    pilot:
      traceSampling: 0.1  # 链路追踪的采样率
    prometheus:  # 不通过 istio 部署 prometheus，我们会在后续使用 prometheus-operator 来部署
      enabled: false
    gateways:
      istio-ingressgateway:
        type: NodePort  # 本地测试集群用不了 LoadBalancer

