# https://github.com/bitnami/bitnami-docker-mongodb
---
version: '2'

services:
  # 单节点副本集，仅用于测试环境
  mongodb-primary:
    image: 'bitnami/mongodb:4.2'
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0  # 副本集名称
      - MONGODB_REPLICA_SET_MODE=primary
      # 额外的 mongo 参数（设置缓存大小）
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      # 为了让 mongo 在外部可用，必须将 hostname 设为可解析的域名，或者宿主机 IP 地址。
      - MONGODB_ADVERTISED_HOSTNAME=192.168.122.1
      # 安全设置，设置 root 密码与副本集认证密钥
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      # 是否允许空密码，此参数和上面的两个安全相关的环境变量冲突，只能二选一！
      # - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
    - 27017:27017

    # 只需要保存主节点的数据
    # 首次运行时，自动创建的映射文件夹可能有权限问题，注意自行修改。
    volumes:
      - './mongodb_master_data:/bitnami'
