version: "3.4"
services:
  # 单节点副本集，仅测试用！
  mongo1:
    container_name: mongo1
    image: mongo:4.2
    restart: always
    # wiredTigerCacheSizeGB 限制缓存（内存）上限
    entrypoint: ["mongod", "--bind_ip_all", "--replSet=rs0", "--wiredTigerCacheSizeGB=2"]
    volumes:
      - ./mongo-data1:/data/db
    ports:
      - "27017:27017"
    # 利用 healthcheck 进行副本集的自动初始化
    healthcheck: # https://docs.docker.com/compose/compose-file/#healthcheck
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          # 注意：下述命令中的 `mongo.db.local` 必须替换成正确可用的域名！并且客户端能正常解析！
          'rs.initiate( { _id : "rs0",members: [{ _id: 0, host: "mongo.db.local:27017" }] })',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
