version: "3.4"
services:
  # 单节点副本集，仅测试用！
  mongo1:
    container_name: mongo1
    image: mongo:4.2
    restart: always
    # 设置如下两个环境变量（缺一不可），可以创建 root 用户。
    # 注意：启动 mongo 时需要添加 `--auth` 才能强制进行认证。（未测试）
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: change_me
    # wiredTigerCacheSizeGB 限制缓存上限（使用内存），注意要为别的功能预留部分内存。
    entrypoint: ["mongod", "--auth", "--bind_ip_all", "--replSet=rs0", "--wiredTigerCacheSizeGB=2"]
    volumes:
      - ./mongo-data1:/data/db
    ports:
      - "27017:27017"
    # 利用 healthcheck 进行副本集的自动初始化
    healthcheck: # https://docs.docker.com/compose/compose-file/#healthcheck
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          # 注意：下述命令中的 `mongo.db.local` 必须替换成正确可用的域名！并且客户端能正常解析！
          'rs.initiate( { _id : "rs0",members: [{ _id: 0, host: "192.168.5.162:27017" }] })',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
