providers:
  # docker: {}  # 启用 docker provider
  file:
    # 使用单个文件进行配置
    filename: "/etc/traefik/dynamic.yml"
    # 也可以将配置拆分成多个文件，放在一个文件夹中
    # directory: "/etc/traefik/dynamic"

    # 监控配置文件的动态更新，实现配置文件 CURD 的自动热加载。
    watch: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      # 将所有 http 请求重定向到 https
      # 如果要按请求内容决定是否重定向，请通过动态配置(/etc/traefik/dynamic/)来设定。
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# 启用 traefik dashboard，它的路由规则在 dynamic.yml 中配置
api:
  dashboard: true
