# 详见 https://docs.traefik.io/reference/dynamic-configuration/file/
http:
  routers:
    # 配置 traefik dashboard 的入口域名
    api:
      entryPoints:
        - "web"
      # Host 插件的域名必须完全匹配，不支持通配符 *
      rule: "Host(`traefik.local`)"
      # 也支持使用正则表达式，注意正则必须写在 {} 中，并且指定一个没什么用的名称(如 prefix/root/subdomain)
      # rule: "HostRegexp(`{prefix:.+}.traefik.{root:(local|lan|srv)}`)"
      service: api@internal

  services:

# tcp 协议只支持通过 tls 协议的 sni 参数进行路由
# 非 tls 协议，不能分辨数据
tcp:
  routers:
  service:

